global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Token4Good Backend
  - job_name: 'token4good-backend'
    static_configs:
      - targets: ['token4good-backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  # Bitcoin Core (if metrics enabled)
  - job_name: 'bitcoin'
    static_configs:
      - targets: ['token4good-backend:18443']
    scrape_interval: 60s

  # LND
  - job_name: 'lnd'
    static_configs:
      - targets: ['token4good-backend:10009']
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter (if added)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']